export const inspirationAds = [
  {
    id: 1,
    isNew: true,
    adUrl: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0",
    brandUrl: "https://logo.clearbit.com/facebook.com",
    brandLink: "https://facebook.com",
    brandName: "Facebook Marketing",
  },
  {
    id: 2,
    isNew: false,
    adUrl: "https://images.unsplash.com/photo-1557426272-fc759fdf7a8d",
    brandUrl: "https://logo.clearbit.com/instagram.com",
    brandLink: "https://instagram.com",
    brandName: "Instagram Ads",
  },
  {
    id: 3,
    isNew: true,
    adUrl: "https://images.unsplash.com/photo-1552581234-26160f608093",
    brandUrl: "https://logo.clearbit.com/meta.com",
    brandLink: "https://meta.com",
    brandName: "Meta Business",
  },
  {
    id: 4,
    isNew: false,
    adUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692",
    brandUrl: "https://logo.clearbit.com/fb.com",
    brandLink: "https://facebook.com/business",
    brandName: "FB Business",
  },
  {
    id: 5,
    isNew: true,
    adUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf",
    brandUrl: "https://logo.clearbit.com/instagram.com",
    brandLink: "https://instagram.com/business",
    brandName: "IG Business",
  },
  {
    id: 6,
    isNew: true,
    adUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    brandUrl: "https://logo.clearbit.com/meta.com",
    brandLink: "https://meta.com/business",
    brandName: "Meta Marketing",
  },
  {
    id: 7,
    isNew: false,
    adUrl: "https://images.unsplash.com/photo-1600880292089-90a649875c18",
    brandUrl: "https://logo.clearbit.com/facebook.com",
    brandLink: "https://facebook.com/ads",
    brandName: "FB Ads",
  },
  {
    id: 8,
    isNew: true,
    adUrl: "https://images.unsplash.com/photo-1542744094-24638eff58bb",
    brandUrl: "https://logo.clearbit.com/instagram.com",
    brandLink: "https://instagram.com/ads",
    brandName: "Instagram Marketing",
  },
  {
    id: 9,
    isNew: false,
    adUrl: "https://images.unsplash.com/photo-1542744173-05336fcc7ad4",
    brandUrl: "https://logo.clearbit.com/meta.com",
    brandLink: "https://meta.com/ads",
    brandName: "Meta Advertising",
  },
  {
    id: 10,
    isNew: true,
    adUrl: "https://images.unsplash.com/photo-1600880292089-90a649875c18",
    brandUrl: "https://logo.clearbit.com/facebook.com",
    brandLink: "https://facebook.com/marketing",
    brandName: "Facebook Business",
  },
];
